[[redirects]]
from = "/"
to = "/dist/"
status = 200

[[redirects]]
from = "/"
to = "/dist/index.html"
status = 200

[[redirects]]
from = "/index.html"
to = "/dist/index.html"
status = 200

[[redirects]]
from = "/css/baseStyle.min.css"
to = "/dist/css/baseStyle.min.css"
status = 200

[[redirects]]
from = "/app.js"
to = "/dist/app.js"
status = 200

